version: '3.7'
services:
  memebia-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:80
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: