FROM node:12.20.0

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json yarn.lock ./

# Install app dependencies
RUN yarn install

COPY prisma ./prisma/

# Required if not done in postinstall
RUN npx prisma generate

EXPOSE 3000
EXPOSE 9229
ENTRYPOINT ["/app/run-migration.sh"]
CMD [ "npm", "run", "start:dev" ]